name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "pypy3.9"]

    steps:

    - uses: actions/checkout@v5

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install tox

    - run: tox -e py

  docs:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:

    - uses: actions/checkout@v5

    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install tox

    - run: tox -e docs
