name: Tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "pypy3.9"]

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            setup.py
            tox.ini

      - run: pip install tox

      - run: tox -e py

  docs:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            setup.py
            tox.ini

      - run: pip install tox

      - run: tox -e docs
